# Generated by Django 5.0.3 on 2024-04-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
